# Generated by Django 4.1.3 on 2022-11-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='address_ordered_from',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ordered_by',
        ),
    ]
