# Generated by Django 4.1.3 on 2022-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_remove_pizza_address_ordered_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='address_ordered_from',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='pizza',
            name='ordered_by',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pizza',
            name='type_of_pizza',
            field=models.CharField(default='', max_length=99),
        ),
    ]
